# Generated by Django 5.2.15 on 2026-07-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloglar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavhasi')),
                ('shortdesc', models.CharField(max_length=255, verbose_name="Qisqacha ma'lumot")),
                ('longdesc', models.TextField(verbose_name="To'liq ma'lumot")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Bloglar',
            },
        ),
    ]
